// <auto-generated />
using System;
using AutoHuoltoSovellus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoHuoltoSovellus.Migrations
{
    [DbContext(typeof(HuoltoDbContext))]
    [Migration("20250203210834_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Auto", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<DateTime>("ADR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Alkolukko")
                        .HasColumnType("datetime2");

                    b.Property<int>("AutoInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KatsastusPvm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Nopeudenrajoitin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Piirturi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rekisterinumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SäiliöId")
                        .HasColumnType("int");

                    b.HasKey("AutoId");

                    b.HasIndex("SäiliöId");

                    b.ToTable("Autot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.AutoHuollot", b =>
                {
                    b.Property<int>("HuollonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HuollonId"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("HuollonKuvaus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("HuollonTyyppi")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HuoltoPaikka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HuoltoPvm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HuoltopaikatHuoltopaikkaId")
                        .HasColumnType("int");

                    b.HasKey("HuollonId");

                    b.HasIndex("AutoId");

                    b.HasIndex("HuoltopaikatHuoltopaikkaId");

                    b.ToTable("AutoHuollot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.AutoInfo", b =>
                {
                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("InfoTxt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutoId");

                    b.ToTable("AutoInfot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Huoltopaikat", b =>
                {
                    b.Property<int>("HuoltopaikkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HuoltopaikkaId"));

                    b.Property<string>("Huoltopaikka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HuoltopaikkaId");

                    b.ToTable("Huoltopaikat");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Kuva", b =>
                {
                    b.Property<int>("KuvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KuvaId"));

                    b.Property<int>("AutoInfoId")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<byte[]>("KuvaData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("KuvaNimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuvaTyyppi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerävaunuInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SäiliöInfoId")
                        .HasColumnType("int");

                    b.HasKey("KuvaId");

                    b.ToTable("Kuvat");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Perävaunu", b =>
                {
                    b.Property<int>("PerävaunuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerävaunuId"));

                    b.Property<DateTime>("ADR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KatsastusPvm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Määräaikaistarkastus")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerävaunuInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Rekisterinumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Välitarkastus")
                        .HasColumnType("datetime2");

                    b.HasKey("PerävaunuId");

                    b.ToTable("Perävaunut");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.PerävaunuHuollot", b =>
                {
                    b.Property<int>("HuollonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HuollonId"));

                    b.Property<string>("HuollonKuvaus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("HuollonTyyppi")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HuoltoPaikka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HuoltoPvm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HuoltopaikatHuoltopaikkaId")
                        .HasColumnType("int");

                    b.Property<int>("PerävaunuId")
                        .HasColumnType("int");

                    b.HasKey("HuollonId");

                    b.HasIndex("HuoltopaikatHuoltopaikkaId");

                    b.HasIndex("PerävaunuId");

                    b.ToTable("PerävaunuHuollot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.PerävaunuInfo", b =>
                {
                    b.Property<int>("PerävaunuId")
                        .HasColumnType("int");

                    b.Property<string>("InfoTxt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PerävaunuId");

                    b.ToTable("PerävaunuInfot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Säiliö", b =>
                {
                    b.Property<int>("SäiliöId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SäiliöId"));

                    b.Property<DateTime>("Määräaikaistarkastus")
                        .HasColumnType("datetime2");

                    b.Property<int>("SäiliöInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SäiliöNro")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vakaus")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Välitarkastus")
                        .HasColumnType("datetime2");

                    b.HasKey("SäiliöId");

                    b.ToTable("Säiliöt");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.SäiliöHuollot", b =>
                {
                    b.Property<int>("HuollonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HuollonId"));

                    b.Property<string>("HuollonKuvaus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("HuollonTyyppi")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HuoltoPaikka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HuoltoPvm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HuoltopaikatHuoltopaikkaId")
                        .HasColumnType("int");

                    b.Property<int>("SäiliöId")
                        .HasColumnType("int");

                    b.HasKey("HuollonId");

                    b.HasIndex("HuoltopaikatHuoltopaikkaId");

                    b.HasIndex("SäiliöId");

                    b.ToTable("SäiliöHuollot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.SäiliöInfo", b =>
                {
                    b.Property<int>("SäiliöId")
                        .HasColumnType("int");

                    b.Property<string>("InfoTxt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SäiliöId");

                    b.ToTable("SäiliöInfot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Auto", b =>
                {
                    b.HasOne("AutoHuoltoSovellus.Models.Säiliö", "Säiliö")
                        .WithMany()
                        .HasForeignKey("SäiliöId");

                    b.Navigation("Säiliö");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.AutoHuollot", b =>
                {
                    b.HasOne("AutoHuoltoSovellus.Models.Auto", "Auto")
                        .WithMany("Huollot")
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoHuoltoSovellus.Models.Huoltopaikat", null)
                        .WithMany("AutoHuollot")
                        .HasForeignKey("HuoltopaikatHuoltopaikkaId");

                    b.Navigation("Auto");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.AutoInfo", b =>
                {
                    b.HasOne("AutoHuoltoSovellus.Models.Auto", "Auto")
                        .WithOne("AutoInfo")
                        .HasForeignKey("AutoHuoltoSovellus.Models.AutoInfo", "AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.PerävaunuHuollot", b =>
                {
                    b.HasOne("AutoHuoltoSovellus.Models.Huoltopaikat", null)
                        .WithMany("PerävaunuHuollot")
                        .HasForeignKey("HuoltopaikatHuoltopaikkaId");

                    b.HasOne("AutoHuoltoSovellus.Models.Perävaunu", "Perävaunu")
                        .WithMany("Huollot")
                        .HasForeignKey("PerävaunuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perävaunu");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.PerävaunuInfo", b =>
                {
                    b.HasOne("AutoHuoltoSovellus.Models.Perävaunu", "Perävaunu")
                        .WithOne("PerävaunuInfo")
                        .HasForeignKey("AutoHuoltoSovellus.Models.PerävaunuInfo", "PerävaunuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perävaunu");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.SäiliöHuollot", b =>
                {
                    b.HasOne("AutoHuoltoSovellus.Models.Huoltopaikat", null)
                        .WithMany("SäiliöHuollot")
                        .HasForeignKey("HuoltopaikatHuoltopaikkaId");

                    b.HasOne("AutoHuoltoSovellus.Models.Säiliö", "Säiliö")
                        .WithMany("Huollot")
                        .HasForeignKey("SäiliöId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Säiliö");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.SäiliöInfo", b =>
                {
                    b.HasOne("AutoHuoltoSovellus.Models.Säiliö", "Säiliö")
                        .WithOne("SäiliöInfo")
                        .HasForeignKey("AutoHuoltoSovellus.Models.SäiliöInfo", "SäiliöId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Säiliö");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Auto", b =>
                {
                    b.Navigation("AutoInfo");

                    b.Navigation("Huollot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Huoltopaikat", b =>
                {
                    b.Navigation("AutoHuollot");

                    b.Navigation("PerävaunuHuollot");

                    b.Navigation("SäiliöHuollot");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Perävaunu", b =>
                {
                    b.Navigation("Huollot");

                    b.Navigation("PerävaunuInfo");
                });

            modelBuilder.Entity("AutoHuoltoSovellus.Models.Säiliö", b =>
                {
                    b.Navigation("Huollot");

                    b.Navigation("SäiliöInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
